apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: postgres-data
  namespace: todok8s

spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: manual

  resources:
    requests:
      storage: 1Gi