apiVersion: apps/v1
kind: Deployment

metadata:
  name: todo-backend
  namespace: todok8s

spec:
  replicas: 2

  selector:
    matchLabels:
      app: todo-backend

  template:
    metadata:
      labels:
        app: todo-backend

    spec:
      imagePullSecrets:
        - name: ghcr-secret

      containers:
        - name: backend
          image: ghcr.io/neskazu/todok8s-backend:1.0

          ports:
            - containerPort: 8000

          envFrom:
            - configMapRef:
                name: todok8s-config

            - secretRef:
                name: todok8s-db-secret

          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5