Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  config.vm.define "k8s-control" do |node|
    node.vm.hostname = "k8s-control"
    node.vm.network "private_network", ip: "192.168.56.10"

    node.vm.provider "virtualbox" do |vb|
      vb.name = "k8s-control"
      vb.memory = 2048
      vb.cpus = 2
    end
  end

  config.vm.define "k8s-worker" do |node|
    node.vm.hostname = "k8s-worker"
    node.vm.network "private_network", ip: "192.168.56.11"

    node.vm.provider "virtualbox" do |vb|
      vb.name = "k8s-worker"
      vb.memory = 2048
      vb.cpus = 2
    end
  end
end